import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "./globals.css";
import { AuthProvider } from "./providers/authContext/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tohano",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
       <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </AuthProvider>
   
  );
}
